<?xml version="1.0" encoding="utf-8"?><Database Name="TheHouse_dev" Class="ProductDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=TheHouse_dev;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MySqlConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.view_Product" Member="view_Products">
    <Type Name="view_Product">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MOQ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MOQUnit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductionLeadTime" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SellingPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DiscountPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ShippingFee" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Height" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Width" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Depth" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SellingStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellingEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Lang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FunctionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="fileUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="fileUrl2" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LongDescription" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NavigateUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="VideoUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Video3D" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CameraModel" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FunctionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MOQ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MOQUnit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductionLeadTime" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SellingPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DiscountPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ShippingFee" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Height" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Width" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Depth" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SellingStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellingEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fileUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="NavigateUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="VideoUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Video3D" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CameraModel" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductImage" Member="ProductImages">
    <Type Name="ProductImage">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThumbnailWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThumbnailHeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductName" Member="ProductNames">
    <Type Name="ProductName">
      <Column Name="ProductNameID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Lang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="fileUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LongDescription" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="fileUrl2" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductSize" Member="ProductSizes">
    <Type Name="ProductSize">
      <Column Name="SizeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductTag" Member="ProductTags">
    <Type Name="ProductTag">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TagID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Comment" Member="Comments">
    <Type Name="Comment">
      <Column Name="CommentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CommentType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReferenceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CommentDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CommentDescription" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="IsInspected" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MediaUrl" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="MediaTitle" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="MediaDesc" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LikeTable" Member="LikeTables">
    <Type Name="LikeTable">
      <Column Name="LikeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LikeType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReferenceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tag" Member="Tags">
    <Type Name="Tag">
      <Column Name="TagID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tag" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TagGroup" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FunctionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TagName" Member="TagNames">
    <Type Name="TagName">
      <Column Name="TagNameID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TagID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Lang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TagName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.view_Tag" Member="view_Tags">
    <Type Name="view_Tag">
      <Column Name="TagID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tag" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TagGroup" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Lang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TagName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FunctionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.view_ProductTag" Member="view_ProductTags">
    <Type Name="view_ProductTag">
      <Column Name="ProductID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TagID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tag" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TagGroup" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Lang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TagName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.view_LikeTableCount" Member="view_LikeTableCounts">
    <Type Name="view_LikeTableCount">
      <Column Name="Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LikeType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReferenceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.view_LikeTableCountByUser" Member="view_LikeTableCountByUsers">
    <Type Name="view_LikeTableCountByUser">
      <Column Name="LikeCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LikeType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReferenceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.view_Comment" Member="view_Comments">
    <Type Name="view_Comment">
      <Column Name="CommentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CommentType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReferenceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CommentDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CommentDescription" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="IsInspected" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MediaUrl" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="MediaTitle" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="MediaDesc" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="UserPicUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LikeCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.OpinionLeader" Member="OpinionLeaders">
    <Type Name="OpinionLeader">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OLUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="OLFollower" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ViewCount" Member="ViewCounts">
    <Type Name="ViewCount">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReferenceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ViewCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastView" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Viewer" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Device" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductDetail" Member="ProductDetails">
    <Type Name="ProductDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Vintage" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Grape" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Alcohol" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Volume" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Winery" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InternationalRatings" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.view_ProductImage" Member="view_ProductImages">
    <Type Name="view_ProductImage">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SellingStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellingEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThumbnailWidth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThumbnailHeight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FunctionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="fileUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="MOQUnit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LongDescription" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NavigateUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="VideoUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CameraModel" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SellingPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.view_productDetail" Member="view_productDetails">
    <Type Name="view_productDetail">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SellingStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellingEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThumbnailWidth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThumbnailHeight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FunctionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="fileUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="MOQUnit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LongDescription" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NavigateUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="VideoUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CameraModel" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SellingPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Vintage" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Grape" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Alcohol" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Volume" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Winery" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InternationalRatings" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.view_ProductImageTag" Member="view_ProductImageTags">
    <Type Name="view_ProductImageTag">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SellingStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SellingEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThumbnailWidth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThumbnailHeight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FunctionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="fileUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="MOQUnit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="TagID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SellingPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MemberDetail" Member="MemberDetails">
    <Type Name="MemberDetail">
      <Column Name="UserID" Type="System.String" DbType="VarChar(256) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ContactNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryAddress" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FacebookUserID" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UserPicUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UserDesc" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UserWebsite" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GooglePlusUserID" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="WeiboUserID" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="TwitterUserID" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SiteFunction" Member="SiteFunctions">
    <Type Name="SiteFunction">
      <Column Name="FunctionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FunctionName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="hasCategory" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DefaultCategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hasCategoryImage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CategoryThumbnailWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryThumbnailHeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryThumbnailNoImage" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="CategoryMaxLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryImageWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryImageHeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryImageNoImage" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="hasProductImage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProductThumbnailWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductThumbnailHeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductThumbnailNoImage" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="ProductImageWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductImageHeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductImageCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductImageNoImage" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="hasProductCode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="hasDetails" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="hasPrice" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="hasDateRange" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="hasTag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AllowUser" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="hasFile" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="hasDescription" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HTMLDescription" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CategoryImageOptional" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProductImageOptional" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CategoryIOSImageWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryIOSImageHeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryAndroidImageWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryAndroidImageHeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductIOSThumbnailWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductIOSThumbnailHeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductIOSImageWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductIOSImageHeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductAndroidThumbnailWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductAndroidThumbnailHeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductAndroidImageWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductAndroidImageHeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hasLink" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CategoryCaptionList" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="hasUrl" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="hasVideo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RestaurantDetail" Member="RestaurantDetails">
    <Type Name="RestaurantDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GoogleMap" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SingleUse" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RestMenu" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Cuisine" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AvgExpense" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="SeatsNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WineStock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayMethod" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RestaurantEventDateTime" Member="RestaurantEventDateTimes">
    <Type Name="RestaurantEventDateTime">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FromDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ToDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.view_RestaurantDetail" Member="view_RestaurantDetails">
    <Type Name="view_RestaurantDetail">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GoogleMap" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SingleUse" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Cuisine" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RestMenu" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="AvgExpense" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="SeatsNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WineStock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayMethod" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductRelated" Member="ProductRelateds">
    <Type Name="ProductRelated">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RelatedID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="RelatedType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EventDetail" Member="EventDetails">
    <Type Name="EventDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EventPrice" Type="System.Decimal" DbType="Decimal(7,2) NOT NULL" CanBeNull="false" />
      <Column Name="GlassPrice1" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="GlassVolume1" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="GlassPrice2" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="GlassVolume2" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="GlassPrice3" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="GlassVolume3" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="MaxAttend" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MenuUrl" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderForm" Member="OrderForms">
    <Type Name="OrderForm">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ContactPhone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryAddress" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentMethod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryMethod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="TransactionRefNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PaidDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PayPalStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Lang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdateUser" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.OrderItem" Member="OrderItems">
    <Type Name="OrderItem">
      <Column Name="OrderItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderProductCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderProductName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="OrderQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="OrderShippingFee" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.OrderStatus" Member="OrderStatus">
    <Type Name="OrderStatus">
      <Column Name="OrderStatusCode" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ColorCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.OrderStatusLang" Member="OrderStatusLangs">
    <Type Name="OrderStatusLang">
      <Column Name="OrderStatusCode" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Lang" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentMethod" Member="PaymentMethods">
    <Type Name="PaymentMethod">
      <Column Name="PaymentMethodId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PaymentMethodName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentPage" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentMethodLang" Member="PaymentMethodLangs">
    <Type Name="PaymentMethodLang">
      <Column Name="LangPaymentMethodId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PaymentMethodId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Lang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LangPaymentMethod" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LangDescription" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.PayPalLog" Member="PayPalLogs">
    <Type Name="PayPalLog">
      <Column Name="PayPalLogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="receiver_email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="receiver_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="residence_country" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="transaction_subject" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="txn_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="txn_type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="payer_email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="payer_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="payer_status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="last_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="address_city" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="address_country" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="address_country_code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="address_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="address_state" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="address_status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="address_street" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="address_zip" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="custom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="handling_amount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="item_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="item_number" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mc_currency" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mc_fee" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="mc_gross" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="payment_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="payment_fee" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="payment_gross" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="payment_status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="payment_type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="shipping" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="tax" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="verify_sign" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PayPalStatusMap" Member="PayPalStatusMaps">
    <Type Name="PayPalStatusMap">
      <Column Name="PayPalStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderStatusCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PayPalDescription" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.EventUser" Member="EventUsers">
    <Type Name="EventUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InviteBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EventStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </Type>
  </Table>
</Database>